# Generated by Django 5.1.7 on 2025-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True, help_text='A brief summary of the post', max_length=500, null=True),
        ),
    ]
