# Generated by Django 5.1.7 on 2025-04-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
    ]
