# Generated by Django 5.2 on 2025-04-07 15:40

from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=CKEditor5Field(config_name='extends'),
        ),
    ]
