# Generated by Django 5.2 on 2025-04-07 16:30

from django.db import migrations
import os
import shutil
from django.conf import settings

def move_images(apps, schema_editor):
    # Get the Post model
    Post = apps.get_model('posts', 'Post')
    
    # Create the new directory if it doesn't exist
    new_dir = os.path.join(settings.MEDIA_ROOT, 'post_images')
    os.makedirs(new_dir, exist_ok=True)
    
    # Move each image
    for post in Post.objects.all():
        if post.image:
            # Get the old and new paths
            old_path = os.path.join(settings.MEDIA_ROOT, str(post.image))
            new_path = os.path.join(settings.MEDIA_ROOT, 'post_images', os.path.basename(str(post.image)))
            
            # Move the file if it exists
            if os.path.exists(old_path):
                os.makedirs(os.path.dirname(new_path), exist_ok=True)
                shutil.move(old_path, new_path)
                
                # Update the database
                post.image = f'post_images/{os.path.basename(str(post.image))}'
                post.save()

def reverse_move(apps, schema_editor):
    # Get the Post model
    Post = apps.get_model('posts', 'Post')
    
    # Move each image back
    for post in Post.objects.all():
        if post.image:
            # Get the old and new paths
            new_path = os.path.join(settings.MEDIA_ROOT, str(post.image))
            old_path = os.path.join(settings.MEDIA_ROOT, 'uploads', os.path.basename(str(post.image)))
            
            # Move the file if it exists
            if os.path.exists(new_path):
                os.makedirs(os.path.dirname(old_path), exist_ok=True)
                shutil.move(new_path, old_path)
                
                # Update the database
                post.image = f'uploads/{os.path.basename(str(post.image))}'
                post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_image'),
    ]

    operations = [
        migrations.RunPython(move_images, reverse_move),
    ]
