# Generated by Django 4.2 on 2025-04-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_move_existing_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
