# Generated by Django 4.2 on 2025-04-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
