# Generated by Django 5.2 on 2025-04-07 16:25

from django.db import migrations
from django.contrib.auth.models import User
from author.models import UserProfile


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('author', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
